[build]
command = "streamlit run app.py"
publish = "."

[context.production]
node_env = "production"

[build.environment]
# This will ensure that the `streamlit` package is installed in the virtual environment
python = "python3.9"

# This will ensure that the `requirements.txt` file is installed in the virtual environment
# before the build command is run
install = ["pip3 install -r requirements.txt"]

[author]
name = "Aayush Soni"
email = "aayushsoni424@gmail.com"